sudo: false
language: python
env:
  - TOKENV=py24
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py34
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python2.4
install:
  - pip install tox PyYAML Jinja2 sphinx
script:
- if test x"$TOKENV" != x'py24' ; then  tox ; fi
- if test x"$TOKENV" = x'py24' ; then python2.4 -V && python2.4 -m compileall -fq -x 'module_utils/(a10|rax|openstack|ec2|gce).py' lib/ansible/module_utils ; fi
  #- make -C docsite all
after_success:
  - coveralls
